[package]
name = "soroban-compliance-kit"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
soroban-sdk.workspace = true

[dev-dependencies]
proptest = "1"

[features]
default = []
testutils = ["soroban-sdk/testutils"]
